<?php 

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_boombox-theme-options',
		'title' => 'Boombox Theme Options',
		'fields' => array (
			array (
				'key' => 'field_5332fcea92d85',
				'label' => 'Logo',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5332fcf892d86',
				'label' => 'Logo',
				'name' => 'logo',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_5332fde5618d3',
				'label' => 'Social Icons',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5332fe49d5630',
				'label' => 'Social Icons',
				'name' => 'social_icons',
				'type' => 'select',
				'choices' => array (
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5332fe9cd5631',
				'label' => 'Mailing List',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5332feb5d5632',
				'label' => 'Mailing List Visibility',
				'name' => 'mailing_list_visibility',
				'type' => 'radio',
				'choices' => array (
					'On' => 'On',
					'Off' => 'Off',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5332feced5633',
				'label' => 'Mailing List Title',
				'name' => 'mailing_list_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5332feb5d5632',
							'operator' => '==',
							'value' => 'On',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'Mailing List',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5332fefbd5635',
				'label' => 'Mailing List Placeholder Text',
				'name' => 'mailing_list_placeholder_text',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5332feb5d5632',
							'operator' => '==',
							'value' => 'On',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5332feecd5634',
				'label' => 'Mailing List Button Text',
				'name' => 'mailing_list_button_text',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5332feb5d5632',
							'operator' => '==',
							'value' => 'On',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'Submit',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_home-page-layout',
		'title' => 'Home Page Layout',
		'fields' => array (
			array (
				'key' => 'field_5332f20533b83',
				'label' => 'Sections',
				'name' => 'sections',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Soundcloud Feature',
						'name' => 'soundcloud_feature',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5332f23d33b84',
								'label' => 'Soundcloud iframe code',
								'name' => 'soundcloud_iframe_code',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5332f25a33b85',
								'label' => 'Feature Type',
								'name' => 'feature_type',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'Single' => 'Single',
									'Album' => 'Album',
									'EP' => 'EP',
								),
								'other_choice' => 1,
								'save_other_choice' => 1,
								'default_value' => 'Album',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_5332f28733b86',
								'label' => 'Feature Title',
								'name' => 'feature_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5332f2ab33b87',
								'label' => 'Feature Description',
								'name' => 'feature_description',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => 4,
								'formatting' => 'br',
							),
							array (
								'key' => 'field_5332f2c533b88',
								'label' => 'Button Text',
								'name' => 'button_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => 'eg: Purchase',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5332f2d933b89',
								'label' => 'Button URL',
								'name' => 'button_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5332f2f433b8a',
								'label' => 'Background Color',
								'name' => 'background_color',
								'type' => 'color_picker',
								'column_width' => '',
								'default_value' => 'transparent',
							),
						),
					),
					array (
						'label' => 'Video Embed',
						'name' => 'video_embed',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5332f3aa80e51',
								'label' => 'Video Embed Code',
								'name' => 'video_embed_code',
								'type' => 'text',
								'instructions' => 'Fully supports both Youtube and Vimeo iframe embed codes',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5332f3ea80e52',
								'label' => 'Background Color',
								'name' => 'background_color',
								'type' => 'color_picker',
								'column_width' => '',
								'default_value' => '',
							),
						),
					),
					array (
						'label' => 'Custom Text',
						'name' => 'custom_text',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5332f40780e54',
								'label' => 'Text Field',
								'name' => 'text_field',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'basic',
								'media_upload' => 'no',
							),
						),
					),
					array (
						'label' => 'Photo Gallery',
						'name' => 'photo_gallery',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5332f42480e56',
								'label' => 'Photos',
								'name' => 'photos',
								'type' => 'gallery',
								'column_width' => '',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
						),
					),
				),
				'button_label' => 'Add Section',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'featured_image',
			),
		),
		'menu_order' => 0,
	));
}